// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package io.grpc.project.smarthome.speakers;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool val = 1;</code>
   */
  boolean getVal();
}
