// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package io.grpc.project.smarthome.speakers;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 volume = 1;</code>
   */
  int getVolume();
}
