// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package io.grpc.project.smarthome.speakers;

public interface IntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.IntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numInput = 1;</code>
   */
  int getNumInput();
}
