// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speakers.proto

package io.grpc.project.smarthome.speakers;

public final class SpeakersServiceImpl {
  private SpeakersServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_IntResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016speakers.proto\022\tsmarthome\"\034\n\rStringReq" +
      "uest\022\013\n\003val\030\001 \001(\t\"\035\n\016StringResponse\022\013\n\003v" +
      "al\030\001 \001(\t\"\035\n\016BooleanRequest\022\013\n\003val\030\001 \001(\010\"" +
      "\036\n\nIntRequest\022\020\n\010numInput\030\001 \001(\005\"\035\n\013IntRe" +
      "sponse\022\016\n\006volume\030\001 \001(\0052\357\001\n\017SpeakersServi" +
      "ce\022H\n\016turnOnSpeakers\022\031.smarthome.Boolean" +
      "Request\032\031.smarthome.StringResponse\"\000\022I\n\r" +
      "displayInputs\022\031.smarthome.BooleanRequest" +
      "\032\031.smarthome.StringResponse\"\0000\001\022G\n\017devic" +
      "eDetection\022\030.smarthome.StringRequest\032\026.s" +
      "marthome.IntResponse\"\000(\001B;\n\"io.grpc.proj" +
      "ect.smarthome.speakersB\023SpeakersServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthome_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthome_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthome_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarthome_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_BooleanRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smarthome_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_IntRequest_descriptor,
        new java.lang.String[] { "NumInput", });
    internal_static_smarthome_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smarthome_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_IntResponse_descriptor,
        new java.lang.String[] { "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
