// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tv.proto

package io.grpc.project.smarthome.tv;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numOutput = 1;</code>
   */
  int getNumOutput();
}
