// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tv.proto

package io.grpc.project.smarthome.tv;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringResponseValue = 1;</code>
   */
  java.lang.String getStringResponseValue();
  /**
   * <code>string stringResponseValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringResponseValueBytes();

  /**
   * <code>string stringResponseValue2 = 2;</code>
   */
  java.lang.String getStringResponseValue2();
  /**
   * <code>string stringResponseValue2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getStringResponseValue2Bytes();
}
