// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tv.proto

package io.grpc.project.smarthome.tv;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
