// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tv.proto

package io.grpc.project.smarthome.tv;

public final class TvServiceImpl {
  private TvServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_IntResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010tv.proto\022\tsmarthome\"+\n\rStringRequest\022\032" +
      "\n\022stringRequestValue\030\001 \001(\t\"-\n\016BooleanReq" +
      "uest\022\033\n\023booleanRequestValue\030\001 \001(\010\"-\n\016Str" +
      "ingResponse\022\033\n\023stringResponseValue\030\001 \001(\t" +
      "\"\036\n\nIntRequest\022\020\n\010numInput\030\001 \001(\005\" \n\013IntR" +
      "esponse\022\021\n\tnumOutput\030\001 \001(\0052\332\003\n\tTvService" +
      "\022@\n\006turnOn\022\031.smarthome.BooleanRequest\032\031." +
      "smarthome.StringResponse\"\000\022M\n\022displayCha" +
      "nnelList\022\030.smarthome.StringRequest\032\031.sma" +
      "rthome.StringResponse\"\0000\001\022C\n\016increaseVol" +
      "ume\022\025.smarthome.IntRequest\032\026.smarthome.I" +
      "ntResponse\"\000(\001\022H\n\013liveContent\022\030.smarthom" +
      "e.StringRequest\032\031.smarthome.StringRespon" +
      "se\"\000(\0010\001\022U\n\034displayInputsSpeakersCommand" +
      "\022\030.smarthome.StringRequest\032\031.smarthome.S" +
      "tringResponse\"\000\022V\n\035musicStreamingSpeaker" +
      "sCommand\022\030.smarthome.StringRequest\032\031.sma" +
      "rthome.StringResponse\"\000B/\n\034io.grpc.proje" +
      "ct.smarthome.tvB\rTvServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthome_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthome_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringRequest_descriptor,
        new java.lang.String[] { "StringRequestValue", });
    internal_static_smarthome_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthome_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_BooleanRequest_descriptor,
        new java.lang.String[] { "BooleanRequestValue", });
    internal_static_smarthome_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarthome_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringResponse_descriptor,
        new java.lang.String[] { "StringResponseValue", });
    internal_static_smarthome_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smarthome_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_IntRequest_descriptor,
        new java.lang.String[] { "NumInput", });
    internal_static_smarthome_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smarthome_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_IntResponse_descriptor,
        new java.lang.String[] { "NumOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
