// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtain.proto

package io.grpc.project.smarthome.curtain;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanRequestValue = 1;</code>
   */
  boolean getBooleanRequestValue();
}
