// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtain.proto

package io.grpc.project.smarthome.curtain;

public final class CurtainServiceImpl {
  private CurtainServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeightAndWidth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeightAndWidth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcurtain.proto\"+\n\rStringRequest\022\032\n\022stri" +
      "ngRequestValue\030\001 \001(\t\"-\n\016BooleanRequest\022\033" +
      "\n\023booleanRequestValue\030\001 \001(\010\"-\n\016StringRes" +
      "ponse\022\033\n\023stringResponseValue\030\001 \001(\t\"/\n\016He" +
      "ightAndWidth\022\016\n\006height\030\001 \001(\002\022\r\n\005width\030\002 " +
      "\001(\0022\243\001\n\016CurtainService\022)\n\004open\022\016.StringR" +
      "equest\032\017.StringResponse\"\000\022*\n\005close\022\016.Str" +
      "ingRequest\032\017.StringResponse\"\000\022:\n\024adjustH" +
      "eightAndWidth\022\017.HeightAndWidth\032\017.StringR" +
      "esponse\"\000B9\n!io.grpc.project.smarthome.c" +
      "urtainB\022CurtainServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StringRequest_descriptor,
        new java.lang.String[] { "StringRequestValue", });
    internal_static_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BooleanRequest_descriptor,
        new java.lang.String[] { "BooleanRequestValue", });
    internal_static_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StringResponse_descriptor,
        new java.lang.String[] { "StringResponseValue", });
    internal_static_HeightAndWidth_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeightAndWidth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeightAndWidth_descriptor,
        new java.lang.String[] { "Height", "Width", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
