// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtain.proto

package io.grpc.project.smarthome.curtain;

public interface HeightAndWidthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeightAndWidth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float height = 1;</code>
   */
  float getHeight();

  /**
   * <code>float width = 2;</code>
   */
  float getWidth();
}
