// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtain.proto

package io.grpc.project.smarthome.curtain;

/**
 * Protobuf type {@code HeightAndWidth}
 */
public  final class HeightAndWidth extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HeightAndWidth)
    HeightAndWidthOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeightAndWidth.newBuilder() to construct.
  private HeightAndWidth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeightAndWidth() {
    height_ = 0F;
    width_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeightAndWidth(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            height_ = input.readFloat();
            break;
          }
          case 21: {

            width_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.project.smarthome.curtain.CurtainServiceImpl.internal_static_HeightAndWidth_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.project.smarthome.curtain.CurtainServiceImpl.internal_static_HeightAndWidth_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.project.smarthome.curtain.HeightAndWidth.class, io.grpc.project.smarthome.curtain.HeightAndWidth.Builder.class);
  }

  public static final int HEIGHT_FIELD_NUMBER = 1;
  private float height_;
  /**
   * <code>float height = 1;</code>
   */
  public float getHeight() {
    return height_;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private float width_;
  /**
   * <code>float width = 2;</code>
   */
  public float getWidth() {
    return width_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (height_ != 0F) {
      output.writeFloat(1, height_);
    }
    if (width_ != 0F) {
      output.writeFloat(2, width_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (height_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, height_);
    }
    if (width_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, width_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.project.smarthome.curtain.HeightAndWidth)) {
      return super.equals(obj);
    }
    io.grpc.project.smarthome.curtain.HeightAndWidth other = (io.grpc.project.smarthome.curtain.HeightAndWidth) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getHeight())
        == java.lang.Float.floatToIntBits(
            other.getHeight()));
    result = result && (
        java.lang.Float.floatToIntBits(getWidth())
        == java.lang.Float.floatToIntBits(
            other.getWidth()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHeight());
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWidth());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.project.smarthome.curtain.HeightAndWidth parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.project.smarthome.curtain.HeightAndWidth prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeightAndWidth}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeightAndWidth)
      io.grpc.project.smarthome.curtain.HeightAndWidthOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.project.smarthome.curtain.CurtainServiceImpl.internal_static_HeightAndWidth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.project.smarthome.curtain.CurtainServiceImpl.internal_static_HeightAndWidth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.project.smarthome.curtain.HeightAndWidth.class, io.grpc.project.smarthome.curtain.HeightAndWidth.Builder.class);
    }

    // Construct using io.grpc.project.smarthome.curtain.HeightAndWidth.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      height_ = 0F;

      width_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.project.smarthome.curtain.CurtainServiceImpl.internal_static_HeightAndWidth_descriptor;
    }

    @java.lang.Override
    public io.grpc.project.smarthome.curtain.HeightAndWidth getDefaultInstanceForType() {
      return io.grpc.project.smarthome.curtain.HeightAndWidth.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.project.smarthome.curtain.HeightAndWidth build() {
      io.grpc.project.smarthome.curtain.HeightAndWidth result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.project.smarthome.curtain.HeightAndWidth buildPartial() {
      io.grpc.project.smarthome.curtain.HeightAndWidth result = new io.grpc.project.smarthome.curtain.HeightAndWidth(this);
      result.height_ = height_;
      result.width_ = width_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.project.smarthome.curtain.HeightAndWidth) {
        return mergeFrom((io.grpc.project.smarthome.curtain.HeightAndWidth)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.project.smarthome.curtain.HeightAndWidth other) {
      if (other == io.grpc.project.smarthome.curtain.HeightAndWidth.getDefaultInstance()) return this;
      if (other.getHeight() != 0F) {
        setHeight(other.getHeight());
      }
      if (other.getWidth() != 0F) {
        setWidth(other.getWidth());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.project.smarthome.curtain.HeightAndWidth parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.project.smarthome.curtain.HeightAndWidth) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float height_ ;
    /**
     * <code>float height = 1;</code>
     */
    public float getHeight() {
      return height_;
    }
    /**
     * <code>float height = 1;</code>
     */
    public Builder setHeight(float value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float height = 1;</code>
     */
    public Builder clearHeight() {
      
      height_ = 0F;
      onChanged();
      return this;
    }

    private float width_ ;
    /**
     * <code>float width = 2;</code>
     */
    public float getWidth() {
      return width_;
    }
    /**
     * <code>float width = 2;</code>
     */
    public Builder setWidth(float value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float width = 2;</code>
     */
    public Builder clearWidth() {
      
      width_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HeightAndWidth)
  }

  // @@protoc_insertion_point(class_scope:HeightAndWidth)
  private static final io.grpc.project.smarthome.curtain.HeightAndWidth DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.project.smarthome.curtain.HeightAndWidth();
  }

  public static io.grpc.project.smarthome.curtain.HeightAndWidth getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeightAndWidth>
      PARSER = new com.google.protobuf.AbstractParser<HeightAndWidth>() {
    @java.lang.Override
    public HeightAndWidth parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeightAndWidth(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeightAndWidth> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeightAndWidth> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.project.smarthome.curtain.HeightAndWidth getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

