// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtain.proto

package io.grpc.project.smarthome.curtain;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringResponseValue = 1;</code>
   */
  java.lang.String getStringResponseValue();
  /**
   * <code>string stringResponseValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringResponseValueBytes();
}
