// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarthome.proto

package io.grpc.project.smarthome;

public final class SmartHomeServiceImpl {
  private SmartHomeServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017smarthome.proto\022\tsmarthome\"\034\n\rStringRe" +
      "quest\022\013\n\003val\030\001 \001(\t\"\035\n\016StringResponse\022\013\n\003" +
      "val\030\001 \001(\t2[\n\020SmartHomeService\022G\n\016makeCon" +
      "nection\022\030.smarthome.StringRequest\032\031.smar" +
      "thome.StringResponse\"\000B3\n\031io.grpc.projec" +
      "t.smarthomeB\024SmartHomeServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthome_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthome_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthome_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
