// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarthome.proto

package io.grpc.project.smarthome;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
