// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.project.smarthome.lights;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanValue = 1;</code>
   */
  boolean getBooleanValue();
}
