// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.project.smarthome.lights;

public final class LightsServiceImpl {
  private LightsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthome_Modes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthome_Modes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lights.proto\022\tsmarthome\"\034\n\rStringReque" +
      "st\022\013\n\003val\030\001 \001(\t\"\035\n\016StringResponse\022\013\n\003val" +
      "\030\001 \001(\t\"\035\n\016BooleanRequest\022\013\n\003val\030\001 \001(\010\"V\n" +
      "\005Modes\022%\n\006detail\030\001 \001(\0162\025.smarthome.Modes" +
      ".Mode\"&\n\004Mode\022\t\n\005LIGHT\020\000\022\010\n\004DARK\020\001\022\t\n\005DI" +
      "SCO\020\0022\255\002\n\rLightsService\022E\n\013lightSwitch\022\031" +
      ".smarthome.BooleanRequest\032\031.smarthome.St" +
      "ringResponse\"\000\022L\n\021displayLightModes\022\030.sm" +
      "arthome.StringRequest\032\031.smarthome.String" +
      "Response\"\0000\001\022=\n\014setLightMode\022\020.smarthome" +
      ".Modes\032\031.smarthome.StringResponse\"\000\022H\n\rl" +
      "ightCombiner\022\030.smarthome.StringRequest\032\031" +
      ".smarthome.StringResponse\"\000(\001B7\n io.grpc" +
      ".project.smarthome.lightsB\021LightsService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthome_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthome_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthome_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_StringResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarthome_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_BooleanRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_smarthome_Modes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smarthome_Modes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthome_Modes_descriptor,
        new java.lang.String[] { "Detail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
