// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.project.smarthome.lights;

public interface ModesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.Modes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.smarthome.Modes.Mode detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.smarthome.Modes.Mode detail = 1;</code>
   */
  io.grpc.project.smarthome.lights.Modes.Mode getDetail();
}
