// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package io.grpc.project.smarthome.lights;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthome.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringRequestValue = 1;</code>
   */
  java.lang.String getStringRequestValue();
  /**
   * <code>string stringRequestValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringRequestValueBytes();
}
